export const dummy_posts = [
  {
    id: 1,
    name: "Men's T-Shirt",
    category: "Man",
    subcategory: "Clothing",
    price: 15.99,
    stock: 0,
    description: "Comfortable cotton T-shirt",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 2325,
    name: "Men's Sneakers",
    category: "Man",
    subcategory: "Footwear",
    price: 45.99,
    stock: 50,
    description: "Stylish and durable sneakers",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 3651,
    name: "Men's T-Shirt",
    category: "Man",
    subcategory: "Clothing",
    price: 15.99,
    stock: 0,
    description: "Comfortable cotton T-shirt",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 2563,
    name: "Men's Sneakers",
    category: "Man",
    subcategory: "Footwear",
    price: 45.99,
    stock: 50,
    description: "Stylish and durable sneakers",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 1334,
    name: "Men's T-Shirt",
    category: "Man",
    subcategory: "Clothing",
    price: 15.99,
    stock: 0,
    description: "Comfortable cotton T-shirt",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 222,
    name: "Men's Sneakers",
    category: "Man",
    subcategory: "Footwear",
    price: 45.99,
    stock: 50,
    description: "Stylish and durable sneakers",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 16334,
    name: "Men's T-Shirt",
    category: "Man",
    subcategory: "Clothing",
    price: 15.99,
    stock: 0,
    description: "Comfortable cotton T-shirt",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 23322,
    name: "Men's Sneakers",
    category: "Man",
    subcategory: "Footwear",
    price: 45.99,
    stock: 50,
    description: "Stylish and durable sneakers",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 331,
    name: "Men's T-Shirt",
    category: "Man",
    subcategory: "Clothing",
    price: 15.99,
    stock: 0,
    description: "Comfortable cotton T-shirt",
    rating: 4.5,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 233,
    name: "Men's Sneakers",
    category: "Man",
    subcategory: "Footwear",
    price: 45.99,
    stock: 50,
    description: "Stylish and durable sneakers",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 375,
    name: "Women's Dress",
    category: "Woman",
    subcategory: "Clothing",
    price: 39.99,
    stock: 30,
    description: "Elegant evening dress",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 46587,
    name: "Women's Sandals",
    category: "Woman",
    subcategory: "Footwear",
    price: 25.99,
    stock: 70,
    description: "Comfortable summer sandals",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 375,
    name: "Women's Dress",
    category: "Woman",
    subcategory: "Clothing",
    price: 39.99,
    stock: 0,
    description: "Elegant evening dress",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 46587,
    name: "Women's Sandals",
    category: "Woman",
    subcategory: "Footwear",
    price: 25.99,
    stock: 0,
    description: "Comfortable summer sandals",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 5657,
    name: "Kids' Backpack",
    category: "Kids",
    subcategory: "Accessories",
    price: 19.99,
    stock: 40,
    description: "Colorful and durable backpack",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 6675,
    name: "Kids' Sneakers",
    category: "Kids",
    subcategory: "Footwear",
    price: 29.99,
    stock: 0,
    description: "Lightweight and comfortable",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 5657,
    name: "Kids' Backpack",
    category: "Kids",
    subcategory: "Accessories",
    price: 19.99,
    stock: 40,
    description: "Colorful and durable backpack",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 6675,
    name: "Kids' Sneakers",
    category: "Kids",
    subcategory: "Footwear",
    price: 29.99,
    stock: 0,
    description: "Lightweight and comfortable",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 7235,
    name: "Smartphone",
    category: "Electronics",
    subcategory: "Mobile Phones",
    price: 699.99,
    stock: 0,
    description: "Latest model with advanced features",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 856,
    name: "Laptop",
    category: "Electronics",
    subcategory: "Computers",
    price: 999.99,
    stock: 15,
    description: "High-performance laptop",
    rating: 4.8,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 92546,
    name: "Headphones",
    category: "Electronics",
    subcategory: "Audio",
    price: 49.99,
    stock: 0,
    description: "Noise-cancelling headphones",
    rating: 4.5,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 1325430,
    name: "Smartwatch",
    category: "Electronics",
    subcategory: "Wearable Tech",
    price: 199.99,
    stock: 0,
    description: "Feature-packed smartwatch",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 1431,
    name: "Men's Jacket",
    category: "Man",
    subcategory: "Clothing",
    price: 59.99,
    stock: 0,
    description: "Warm and stylish jacket",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 15642,
    name: "Women's Handbag",
    category: "Woman",
    subcategory: "Accessories",
    price: 49.99,
    stock: 20,
    description: "Elegant leather handbag",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 14653,
    name: "Kids' T-Shirt",
    category: "Kids",
    subcategory: "Clothing",
    price: 12.99,
    stock: 50,
    description: "Colorful cotton T-shirt",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 1576434,
    name: "Tablet",
    category: "Electronics",
    subcategory: "Tablets",
    price: 399.99,
    stock: 10,
    description: "Portable and powerful tablet",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 53333,
    name: "Women's Dress",
    category: "Woman",
    subcategory: "Clothing",
    price: 39.99,
    stock: 30,
    description: "Elegant evening dress",
    rating: 4.8,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 234,
    name: "Women's Sandals",
    category: "Woman",
    subcategory: "Footwear",
    price: 25.99,
    stock: 70,
    description: "Comfortable summer sandals",
    rating: 4.3,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 523,
    name: "Kids' Backpack",
    category: "Kids",
    subcategory: "Accessories",
    price: 19.99,
    stock: 0,
    description: "Colorful and durable backpack",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 677,
    name: "Kids' Sneakers",
    category: "Kids",
    subcategory: "Footwear",
    price: 29.99,
    stock: 0,
    description: "Lightweight and comfortable",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 777,
    name: "Smartphone",
    category: "Electronics",
    subcategory: "Mobile Phones",
    price: 699.99,
    stock: 20,
    description: "Latest model with advanced features",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 877,
    name: "Laptop",
    category: "Electronics",
    subcategory: "Computers",
    price: 999.99,
    stock: 15,
    description: "High-performance laptop",
    rating: 4.8,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 977,
    name: "Headphones",
    category: "Electronics",
    subcategory: "Audio",
    price: 49.99,
    stock: 60,
    description: "Noise-cancelling headphones",
    rating: 4.5,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 877,
    name: "Laptop",
    category: "Electronics",
    subcategory: "Computers",
    price: 999.99,
    stock: 15,
    description: "High-performance laptop",
    rating: 4.8,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 977,
    name: "Headphones",
    category: "Electronics",
    subcategory: "Audio",
    price: 49.99,
    stock: 60,
    description: "Noise-cancelling headphones",
    rating: 4.5,
    imageUrl: "https://fakeimg.pl/350x200/ff0000,128/000,255",
  },
  {
    id: 107777,
    name: "Smartwatch",
    category: "Electronics",
    subcategory: "Wearable Tech",
    price: 199.99,
    stock: 25,
    description: "Feature-packed smartwatch",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 1177,
    name: "Men's Jacket",
    category: "Man",
    subcategory: "Clothing",
    price: 59.99,
    stock: 40,
    description: "Warm and stylish jacket",
    rating: 4.6,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 127,
    name: "Women's Handbag",
    category: "Woman",
    subcategory: "Accessories",
    price: 49.99,
    stock: 20,
    description: "Elegant leather handbag",
    rating: 4.9,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 173,
    name: "Kids' T-Shirt",
    category: "Kids",
    subcategory: "Clothing",
    price: 12.99,
    stock: 50,
    description: "Colorful cotton T-shirt",
    rating: 4.4,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
  {
    id: 174,
    name: "Tablet",
    category: "Electronics",
    subcategory: "Tablets",
    price: 399.99,
    stock: 10,
    description: "Portable and powerful tablet",
    rating: 4.7,
    imageUrl: "https://picsum.photos/seed/picsum/200/300",
  },
];
