export const products = [
  {
    id: 1,
    name: "Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: 595,
    image: "https://picsum.photos/200/300",
  },
  {
    id: 2,
    name: "Red Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: 595,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 3,
    name: "Grey Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 4,
    name: "Blue Sports T-shirt",
    brand: "FabriLife",
    price: 595,
    originalPrice: 750,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 5,
    name: "Green Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/400",
  },
  {
    id: 6,
    name: "Light Grey Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/500",
  },
  {
    id: 7,
    name: "Teal Sports T-shirt",
    brand: "FabriLife",
    price: 640,
    originalPrice: null,
    image: "https://picsum.photos/200/300",
  },
  {
    id: 8,
    name: "Dark Blue Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/300",
  },
  {
    id: 14,
    name: "Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: 595,
    image: "https://picsum.photos/200/300",
  },
  {
    id: 24,
    name: "Red Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: 595,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 34,
    name: "Grey Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 44,
    name: "Blue Sports T-shirt",
    brand: "FabriLife",
    price: 595,
    originalPrice: 750,
    image: "https://picsum.photos/id/1/200/300",
  },
  {
    id: 54,
    name: "Green Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/400",
  },
  {
    id: 64,
    name: "Light Grey Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/500",
  },
  {
    id: 74,
    name: "Teal Sports T-shirt",
    brand: "FabriLife",
    price: 640,
    originalPrice: null,
    image: "https://picsum.photos/200/300",
  },
  {
    id: 84,
    name: "Dark Blue Sports T-shirt",
    brand: "FabriLife",
    price: 570,
    originalPrice: null,
    image: "https://picsum.photos/200/300",
  },
];
